version: "3"
services:
  front:
    build:
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./src:/usr/app/src
      - ./public:/usr/app/public
    #env_file:
    #  - ./.env.local
    command:
      "yarn start"